### ISSUE TITLE
Support for the Forks

### ISSUE THREAD

**Issue by TheSpiike** [MrPet/ChiaAddressMonitor#13]
Not an issue at all,  in fact the app works amazing and I have shared with many. 

Initially it would be nice to start with chives, hddcoin and stai then add support for more later.  😉 

Thank you.

**Comment by MrPet** [comment]
The next release will support all forks that are listed on alltheblocks.net . 
It is currently in testing and I have to fix some minor bugs. But in the next two weeks, it should be rolled out.

**Comment by TheSpiike** [comment]
Very Nice to hear!
